---
title: Axes and Legends
---

```{r}
library(gglite)
```

## Axis Customization

### Axis titles

```{r}
g2(mtcars, x = 'mpg', y = 'hp') |>
  mark_point() |>
  axis_of('x', title = 'Miles per Gallon') |>
  axis_of('y', title = 'Horsepower')
```

### Hide an axis

```{r}
g2(mtcars, x = 'mpg', y = 'hp') |>
  mark_point() |>
  axis_of('y', FALSE)
```

### Hide both axes

```{r}
g2(mtcars, x = 'mpg', y = 'hp') |>
  mark_point() |>
  axis_of('x', FALSE) |>
  axis_of('y', FALSE)
```

### Axis with grid

```{r}
g2(mtcars, x = 'mpg', y = 'hp') |>
  mark_point() |>
  axis_of('x', grid = TRUE) |>
  axis_of('y', grid = TRUE)
```

### Axis tick count

```{r}
g2(mtcars, x = 'mpg', y = 'hp') |>
  mark_point() |>
  axis_of('x', tickCount = 5) |>
  axis_of('y', tickCount = 8)
```

## Legend Customization

### Legend position

```{r}
g2(iris, x = 'Sepal.Width', y = 'Sepal.Length', color = 'Species') |>
  mark_point() |>
  legend_of('color', position = 'right')
```

### Legend at the top

```{r}
g2(iris, x = 'Sepal.Width', y = 'Sepal.Length', color = 'Species') |>
  mark_point() |>
  legend_of('color', position = 'top')
```

### Legend at the bottom

```{r}
g2(iris, x = 'Sepal.Width', y = 'Sepal.Length', color = 'Species') |>
  mark_point() |>
  legend_of('color', position = 'bottom')
```

### Legend at the left

```{r}
g2(iris, x = 'Sepal.Width', y = 'Sepal.Length', color = 'Species') |>
  mark_point() |>
  legend_of('color', position = 'left')
```

### Hide a legend

```{r}
g2(iris, x = 'Sepal.Width', y = 'Sepal.Length', color = 'Species') |>
  mark_point() |>
  legend_of('color', FALSE)
```

### Legend with title

```{r}
g2(iris, x = 'Sepal.Width', y = 'Sepal.Length', color = 'Species') |>
  mark_point() |>
  legend_of('color', position = 'right', title = 'Iris Species')
```
